# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-03 03:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phenotypedb', '0023_rnaseq_growth_conditions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accession',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
