# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-06 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phenotypedb', '0024_auto_20200403_0359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observationunit',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
